package com.Echo.NearBuy.common.enums;

public enum OrderStatus {
    PLACED,
    ACCEPTED,
    REJECTED,
    PACKING,
    PACKED,
    WAITING_FOR_DELIVERY_PERSON,
    DELIVERY_REQUESTED,
    DELIVERY_ACCEPTED,
    DELIVERY_UNAVAILABLE,
    DELIVERY_ASSIGNED,
    PICKED_UP,
    OUT_FOR_DELIVERY,
    DELIVERED,
    CANCELLED
}
